// exports.cekResi = require('./cekResi')
// exports.downloader = require('./downloader')
exports.meme = require('./meme')
exports.images = require('./images')
exports.api = require('./api')
exports.translate = require('./translate')
// exports.getLocationData = require('./location')
// exports.edukasi = require('./edukasi')